Repository CusmaLinux/svu, pull requests merged in 2025-05, with the labels that each got.

#21 Filter the entities by type of user in the dashboard
  package-lock.json
  src/main/java/co/edu/itp/svu/config/SecurityConfiguration.java
  src/main/webapp/app/account/account.service.ts
  src/main/webapp/app/entities/entities-menu.component.ts
  src/main/webapp/app/entities/entities-menu.vue
  src/main/webapp/app/router/entities.ts
  src/main/webapp/app/shared/config/store/account-store.ts
Labels: good first issue

#22 Add default fields for pqrs creation
  src/main/java/co/edu/itp/svu/domain/Pqrs.java
  src/main/java/co/edu/itp/svu/repository/OficinaRepository.java
  src/main/java/co/edu/itp/svu/service/PqrsService.java
  src/main/java/co/edu/itp/svu/service/dto/PqrsDTO.java
  src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
  src/main/webapp/app/entities/pqrs/pqrs-update.vue
  src/test/java/co/edu/itp/svu/web/rest/PqrsResourceIT.java
Labels: good first issue

#27 List the active PQRS for the admin and the functionary
  src/main/java/co/edu/itp/svu/repository/PqrsRepository.java
  src/main/java/co/edu/itp/svu/service/PqrsService.java
  src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
Labels: good first issue

#33 Modify view to update PQRS
  src/main/java/co/edu/itp/svu/service/PqrsService.java
  src/main/webapp/app/constants.ts
  src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
  src/main/webapp/app/entities/pqrs/pqrs-update.vue
  src/main/webapp/app/shared/model/pqrs.model.ts
  src/main/webapp/i18n/en/pqrs.json
  src/main/webapp/i18n/es/pqrs.json
Labels: good first issue

#38 Create a security button and modal window to close pqrs
  src/main/java/co/edu/itp/svu/service/PqrsService.java
  src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
  src/main/webapp/app/constants.ts
  src/main/webapp/app/entities/pqrs/pqrs-details.component.ts
  src/main/webapp/app/entities/pqrs/pqrs-details.vue
  src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
  src/main/webapp/app/entities/pqrs/pqrs-update.vue
  src/main/webapp/app/router/entities.ts
  src/main/webapp/i18n/en/global.json
  src/main/webapp/i18n/en/pqrs.json
  src/main/webapp/i18n/es/global.json
  src/main/webapp/i18n/es/pqrs.json
Labels: good first issue

#39 Highlight deadline
  src/main/webapp/app/entities/pqrs/pqrs-details.vue
Labels: good first issue

#40 Prepare release 0.2.0
  CHANGELOG.md
  package.json
  pom.xml
Labels: documentation

#41 Add control of exceptions for methods in notifications services
  package-lock.json
  src/main/java/co/edu/itp/svu/service/NotificacionService.java
Labels: bug

#47 Migration to create new athority and user frontDesk
  src/main/java/co/edu/itp/svu/config/dbmigrations/V007_AddFrontDeskCsAuthority.java
  src/main/java/co/edu/itp/svu/security/AuthoritiesConstants.java
Labels: good first issue
